version: '3'

services:
  server:
    container_name: grpc-micro-api
    build: '.'
    volumes:
      - ./:/grpc-api
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - '3333:3333'
    
  mongodb:
    image: mongo:latest
    container_name: mongodb-api
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
