version: '3'

services:
  server:
    container_name: grpc-microservice
    build: '.'
    volumes:
      - ./:/node-grpc
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'

  db-hidra:
    image: 'mongo'
    container_name: mongodb-hidra
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db-hidra

   db-nix: 'mongo'
   container_name: mongodb-nix
   ports: 
      -  '27017:27017'
    volumes: 
      - ./data/db:/data/db-nix
    
  
